spring.datasource.url=jdbc:mysql://mysql-53cb73e-matrimonial-app.d.aivencloud.com:16895/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_4eyfW9-6IWRNCJy4LpL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect